UdemyAspNetCore/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UdemyAspNetCore.Data;
using UdemyAspNetCore.Models;

namespace UdemyAspNetCore.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ApplicationTypeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.ApplicationType);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType applicationType)
        {
            if (!ModelState.IsValid)
                return View(applicationType);

            _db.ApplicationType.Add(applicationType);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id is null || id == 0)
                return NotFound();

            var applicationType = _db.ApplicationType.Find(id);

            if (applicationType is null)
                return NotFound();

            return View(applicationType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType applicationType)
        {
            if (!ModelState.IsValid)
                return View(applicationType);

            _db.ApplicationType.Update(applicationType);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id is null || id == 0)
                return NotFound();

            var applicationType = _db.ApplicationType.Find(id);

            if (applicationType is null)
                return NotFound();

            return View(applicationType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            if (id is null || id == 0)
                return NotFound();

            var applicationType = _db.ApplicationType.Find(id);

            if (applicationType is null)
                return NotFound();

            _db.ApplicationType.Remove(applicationType);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

UdemyAspNetCore/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;
using UdemyAspNetCore.Data;
using UdemyAspNetCore.Models;
using UdemyAspNetCore.Models.ViewModels;
using UdemyAspNetCore.Utility;

namespace UdemyAspNetCore.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;

        [BindProperty]
        public ProductUserViewModel ProductUserViewModel { get; set; }

        public CartController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment, IEmailSender emailSender)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            var shoppingCartList = new List<ShoppingCart>();
            var sessionShoppingCart = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);

            if (sessionShoppingCart is not null && sessionShoppingCart.Any())
                shoppingCartList = sessionShoppingCart.ToList();

            var prodInCart = shoppingCartList.Select(sc => sc.ProductId).ToList();
            var prodList = _db.Product.Where(p => prodInCart.Contains(p.Id));

            return View(prodList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost()
        {

            return RedirectToAction(nameof(Summary));
        }

/*
 * ВАРИАНТЫ ПОЛУЧЕНИЯ ИМЕНИ ПОЛЬЗОВАТЕЛЯ:
 * 1.
 * var claimsIdentity = (ClaimsIdentity)User.Identity;
 * var claim = claimsIdentity.FindFirst(ClaimTypes.Name);
 * 
 * -------------------------------------------------------
 * 
 * 2.
 * 
 * var userId = User.FindFirstValue(ClaimTypes.Name);
 * 
 * -------------------------------------------------------
 * 
 * 3.
 * 
 * User.Identity.Name
 */

        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var shoppingCartList = new List<ShoppingCart>();
            var sessionShoppingCart = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);

            if (sessionShoppingCart is not null && sessionShoppingCart.Any())
                shoppingCartList = sessionShoppingCart.ToList();

            var prodInCart = shoppingCartList.Select(sc => sc.ProductId).ToList();
            var prodList = _db.Product.Where(p => prodInCart.Contains(p.Id));

            ProductUserViewModel = new ProductUserViewModel()
            {
                ApplicationUser = _db.ApplicationUser.FirstOrDefault(u => u.Id == claim.Value),
                ProductList= prodList.ToList(),
            };

            return View(ProductUserViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(ProductUserViewModel productUserViewModel)
        {
            var pathToTemplate = _webHostEnvironment.WebRootPath
                + Path.DirectorySeparatorChar.ToString()
                + "templates"
                + Path.DirectorySeparatorChar.ToString()
                + "Inquiry.html";

            string subject = "New Inquiry";
            string htmlBody = String.Empty;

            using var sr = System.IO.File.OpenText(pathToTemplate);
            htmlBody = sr.ReadToEnd();

            /*
             * Name: {0}
             * Email: {1}
             * Phone: {2}
             * Products: {3}
             */

            var productListSB = new StringBuilder();

            foreach (var product in productUserViewModel.ProductList)
                productListSB.Append($" - Name: {product.Name} <span style='font-size:14px;'> (ID: {product.Id})</span><br />");
            
            string messageBody = String.Format(htmlBody,
                productUserViewModel.ApplicationUser.FullName,
                productUserViewModel.ApplicationUser.Email,
                productUserViewModel.ApplicationUser.PhoneNumber,
                productListSB.ToString());

            await _emailSender.SendEmailAsync(WC.EmailAdmin, subject, messageBody);

            return RedirectToAction(nameof(InquiryConfirmation));
        }

        public IActionResult InquiryConfirmation()
        {
            HttpContext.Session.Clear();
            return View();
        }

        public IActionResult Remove(int id)
        {
            var shoppingCartList = new List<ShoppingCart>();
            var sessionShoppingCart = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);

            if (sessionShoppingCart is not null && sessionShoppingCart.Any())
                shoppingCartList = sessionShoppingCart.ToList();

            var removedProduct = shoppingCartList.FirstOrDefault(p => p.ProductId == id);
            if (removedProduct is null)
                return BadRequest();

            shoppingCartList.Remove(removedProduct);
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);

            return RedirectToAction(nameof(Index));
        }
    }
}

UdemyAspNetCore/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using UdemyAspNetCore.Data;
using UdemyAspNetCore.Models;

namespace UdemyAspNetCore.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var objList = _db.Category;

            return View(objList);
        }

        //Get - Create
        public IActionResult Create()
        {
            return View();
        }

        //POST - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (!ModelState.IsValid) //Валидация на стороне сервера
                return View(category);

            _db.Category.Add(category);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        //Get - Edit
        public IActionResult Edit(int? id)
        {
            if (id is null || id == 0)
                return NotFound();

            var category = _db.Category.Find(id);

            if (category is null)
                return NotFound();

            return View(category);
        }

        //Post - Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (!ModelState.IsValid) //Валидация на стороне сервера
                return View(category);

            _db.Category.Update(category);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        //Get - Delete
        public IActionResult Delete(int? id)
        {
            if (id is null || id == 0)
                return NotFound();

            var category = _db.Category.Find(id);

            if (category is null)
                return NotFound();

            return View(category);
        }

        //Post - Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var category = _db.Category.Find(id);

            if (category is null) //Валидация на стороне сервера
                return NotFound();

            _db.Category.Remove(category);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

UdemyAspNetCore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UdemyAspNetCore.Data;
using UdemyAspNetCore.Models;
using UdemyAspNetCore.Models.ViewModels;

namespace UdemyAspNetCore.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var objList = _db.Product
                .Include(p => p.Category)
                .Include(p => p.ApplicationType);

            return View(objList);
        }

        //Get - Upsert
        public IActionResult Upsert(int? id)
        {
            var productVM = new ProductViewModel()
            {
                Product = new Product(),
                CategorySelectList = _db.Category.Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
                ApplicationTypeSelectList = _db.ApplicationType.Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }),
            };

            if (id is null)
                return View(productVM);

            productVM.Product = _db.Product.Find(id);

            if (productVM.Product is null)
                return NotFound();

            return View(productVM);
        }

        //POST - Upsert
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductViewModel productVM)
        {
            if (!ModelState.IsValid) //Валидация на стороне сервера
            {
                productVM.CategorySelectList = _db.Category.Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });

                productVM.ApplicationTypeSelectList = _db.ApplicationType.Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });

                return View(productVM);
            }

            var files = HttpContext.Request.Form.Files.ToList();
            string webRootpath = _webHostEnvironment.WebRootPath;

            if (productVM.Product.Id == 0)
            {
                UploadNewImage(productVM, String.Empty, false);

                _db.Product.Add(productVM.Product);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            var objFromDb = _db.Product.AsNoTracking().FirstOrDefault(p => p.Id == productVM.Product.Id);

            if (files.Count > 0)
                UploadNewImage(productVM, objFromDb.Image, true);
            else
                productVM.Product.Image = objFromDb.Image;

            _db.Product.Update(productVM.Product);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        //Get - Delete
        public IActionResult Delete(int? id)
        {
            if (id is null || id == 0)
                return NotFound();

            var product = _db.Product
                .Include(p => p.Category)
                .Include(p => p.ApplicationType)
                .FirstOrDefault(p => p.Id == id);

            if (product is null)
                return NotFound();

            return View(product);
        }

        //Post - Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var product = _db.Product.Find(id);

            if (product is null) //Валидация на стороне сервера
                return NotFound();

            string upload = _webHostEnvironment.WebRootPath + WC.ImagePath;
            string pathToImage = Path.Combine(upload, product.Image);

            if (System.IO.File.Exists(pathToImage))
                System.IO.File.Delete(pathToImage);

            _db.Product.Remove(product);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        private void UploadNewImage(ProductViewModel productVM, string oldImage, bool needDeleteOldImage = false)
        {
            var files = HttpContext.Request.Form.Files.ToList();

            string webRootpath = _webHostEnvironment.WebRootPath;
            string upload = webRootpath + WC.ImagePath;
            string fileName = Guid.NewGuid().ToString();
            string extension = Path.GetExtension(files.FirstOrDefault().FileName);

            var oldFile = Path.Combine(upload, oldImage);

            if (needDeleteOldImage && System.IO.File.Exists(oldFile))
                System.IO.File.Delete(oldFile);

            using var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create);
            files.FirstOrDefault().CopyTo(fileStream);

            productVM.Product.Image = fileName + extension;
        }
    }
}

UdemyAspNetCore/Views/Shared/_IndividualProductCard.cshtml
@model Product

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@String.Format($"{Model.Price:c0}")</span> / sqft</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ImagePath@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 product-card" style="background-color:lavenderblush">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 product-card" style="background-color:aliceblue">@Model.ApplicationType.Name</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesc</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

UdemyAspNetCore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@using UdemyAspNetCore.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UdemyAspNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UdemyAspNetCore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UdemyAspNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-link text-dark">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(WC.AdminRole))
                        {
                            <li class="nav-link dropdown text-dark">
                                <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="nav-item dropdown-menu text-dark">
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">ApplicationType</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li><div class="dropdown-divider"></div></li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-link text-dark">
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) is not null)
                            {
                                        <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;
                                    }
                                            <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                        </a>
                            }
                            else
                            {
                                        <a href="#" class="nav-link" >
                                            <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                        </a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UdemyAspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>